/* Generated by re2c @PACKAGE_VERSION@ on Sun Aug 02 13:38:46 2015 */
#line 1 "main.re"
/* re2c lesson 001_upn_calculator, calc_006, (c) M. Boerger 2006 - 2007 */
#line 36 "main.re"

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define DEBUG(stmt) stmt

int  stack[4];
int  depth = 0;

int push_num(const unsigned char *t, const unsigned char *l, int radix)
{
	int num = 0;
	
	if (depth >= sizeof(stack))
	{
		return 3;
	}

	--t;
	while(++t < l)
	{
		num = num * radix + (*t - (unsigned char)'0');
	}
	DEBUG(printf("Num: %d\n", num));

	stack[depth++] = num;
	return 0;
}

int stack_add()
{
	if (depth < 2) return 4;
	
	--depth;
	stack[depth-1] = stack[depth-1] + stack[depth];
	DEBUG(printf("+\n"));
	return 0;
}

int stack_sub()
{
	if (depth < 2) return 4;

	--depth;
	stack[depth-1] = stack[depth-1] - stack[depth];
	DEBUG(printf("-\n"));
	return 0;
}

int scan(char *s)
{
	unsigned char *p = (unsigned char*)s;
	unsigned char *t;
	int res = 0;
	
#define YYCTYPE         unsigned char
#define YYCURSOR        p
	
	while(!res)
	{
		t = p;

#line 69 "main.c"
		{
			YYCTYPE yych;

			yych = *YYCURSOR;
			switch (yych) {
			case 0x00:	goto yy11;
			case '\t':
			case ' ':	goto yy2;
			case '+':	goto yy7;
			case '-':	goto yy9;
			case '0':	goto yy4;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy6;
			default:	goto yy13;
			}
yy2:
			++YYCURSOR;
			yych = *YYCURSOR;
			goto yy21;
yy3:
#line 107 "main.re"
			{ continue; }
#line 99 "main.c"
yy4:
			++YYCURSOR;
			switch ((yych = *YYCURSOR)) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy17;
			default:	goto yy5;
			}
yy5:
#line 109 "main.re"
			{ res = push_num(t, p, 10); continue; }
#line 118 "main.c"
yy6:
			yych = *++YYCURSOR;
			goto yy16;
yy7:
			++YYCURSOR;
#line 110 "main.re"
			{ res = stack_add();		continue; }
#line 126 "main.c"
yy9:
			++YYCURSOR;
#line 111 "main.re"
			{ res = stack_sub();		continue; }
#line 131 "main.c"
yy11:
			++YYCURSOR;
#line 112 "main.re"
			{ res = depth == 1 ? 0 : 2;	break; }
#line 136 "main.c"
yy13:
			++YYCURSOR;
#line 113 "main.re"
			{ res = 1; 					continue; }
#line 141 "main.c"
yy15:
			++YYCURSOR;
			yych = *YYCURSOR;
yy16:
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy15;
			default:	goto yy5;
			}
yy17:
			++YYCURSOR;
			yych = *YYCURSOR;
			switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':	goto yy17;
			default:	goto yy19;
			}
yy19:
#line 108 "main.re"
			{ res = push_num(t, p, 8);	continue; }
#line 178 "main.c"
yy20:
			++YYCURSOR;
			yych = *YYCURSOR;
yy21:
			switch (yych) {
			case '\t':
			case ' ':	goto yy20;
			default:	goto yy3;
			}
		}
#line 114 "main.re"

	}
	return res;
}

int main(int argc, char **argv)
{
	if (argc > 1)
	{
		char *inp;
		int res = 0, argp = 0, len;
		
		while(!res && ++argp < argc)
		{
			inp = _strdup(argv[argp]);
			len = strlen(inp);
			if (inp[0] == '\"' && inp[len-1] == '\"')
			{
				inp[len - 1] = '\0';
				++inp;
			}
			res = scan(inp);
			free(inp);
		}
		switch(res)
		{
		case 0:
			printf("Result: %d\n", stack[0]);
			return 0;
		case 1:
			fprintf(stderr, "Illegal character in input.\n");
			return 1;
		case 2:
			fprintf(stderr, "Premature end of input.\n");
			return 2;
		case 3:
			fprintf(stderr, "Stack overflow.\n");
			return 3;
		case 4:
			fprintf(stderr, "Stack underflow.\n");
			return 4;
		}
	}
	else
	{
		fprintf(stderr, "%s <expr>\n", argv[0]);
		return 0;
	}
}
